### PR TITLE
Update changes and version

### PR DESCRIPTION
**Pull request by HeroicKatora**
When accepted, I'll release a version based on the latest release here. For the long term: Which team or individual should I transfer the publish rights to?

### CODE REVIEW

**Comment by HeroicKatora** [comment]
I've sent you an invite. You can also publish if you want.

**Comment by Shnatsel** [comment]
I've pushed some changes just now, mostly around reporting cache age and better messaging overall. The notable behavioral change is that cache from the future is now considered invalid.

I think we're good to go.

**Comment by HeroicKatora** [comment]
I don't have permissions to complete the PR so I think you should merge and release :joy:

**Comment by Shnatsel** [comment]
You do now.

**Pull request merged**
