### PR TITLE
Use `xdg` instead of `directories-next`; correct typo in directory name

### PR DESCRIPTION
**Pull request by smoelius**
This PR has two commits:
- The first replaces `directories-next` with `xdg`. (The former seems to have an [uncertain future](https://github.com/xdg-rs/dirs/issues/60).)
- The second corrects a typo I made in #93.

EDIT: I could make these two PRs, or scrap either change, if you prefer.

### CODE REVIEW

**Comment by Shnatsel** [comment]
The dependency change and typo fix look good. Why does this also rename a directory and update references to it?

**Comment by Shnatsel** [comment]
I see. What is the typo fix? I cannot spot it in the diff.

**Comment by Shnatsel** [comment]
Also, CI fails. Please run `rustfmt` to format the code. If that doesn't help please let me know - it's possible that CI version of rustfmt is too old.

**Comment by smoelius** [comment]
> I see. What is the typo fix? I cannot spot it in the diff.

Naming the directory `dep_tests` instead of `deps_tests` is what I am calling a "typo." The fix is to rename the directory to the latter. (Sorry for being unclear.)

**Comment by Shnatsel** [comment]
Ah I see. Thanks! Merging.

**Pull request merged**
