### PR TITLE
Cached data dumps

### PR DESCRIPTION
**Pull request by HeroicKatora**
Downloads the `crates.io` daily data dumps, stores the relevant information in a cache directory and uses that information to read the owner information when possible.

### CODE REVIEW

**Comment by Shnatsel** [comment]
Thanks a lot!

It's early enough in the project that I'm gonna merge now and look later :smile:

**Comment by HeroicKatora** [comment]
@Shnatsel Hint: You need to run `cargo-supply-chain update` to download the data, then the other commands will use them. It does write the publisher data for each individual release as well but that's not yet used.

**Comment by Shnatsel** [comment]
Do they use automatically? I think making it explicit would be nice with something like a `--cached` flag, otherwise it's easy to run `update`, forget about it and then get stale data all of a sudden.

**Comment by Shnatsel** [comment]
Any reason why this uses `libflate` and not `miniz_oxide`?

**Comment by HeroicKatora** [comment]
I did know if `miniz_oxide` had full gzip encapsulation support and did not want to look up the specifics of the header structure or and checksum etc.

**Comment by Shnatsel** [comment]
I see. Nope, you have to use flate2 for that :crying_cat_face:

**Pull request merged**
