### PR TITLE
Upgrade bpaf to 0.7 to remove some turbofishes

### PR DESCRIPTION
**Pull request by pacak**
Plus various code improvements, feel free to drop some or all of them.

### CODE REVIEW

**Comment by pacak** [comment]
Do you want to update the code to use derive macro? This means compiling syn, but it's already being compiled...

**Comment by Shnatsel** [comment]
Thanks! I'll take a look shortly.

Re: derive macro: I'm less concerned about compiling `syn` as I am about the macro being re-run on every compilation, increasing the incremental compilation times. I'm not very familiar with how derive macros work, so if that's not an issue, then using a derive macro to reduce the amount of code would be great.

**Comment by pacak** [comment]
https://github.com/rosetta-rs/argparse-rosetta-rs according to this other than initial cost to compile `syn` and related stuff - there's no difference to incremental compile time.

**Comment by pacak** [comment]
> In that case using the derive API would be great!

Okay. Gimme a day or two.

**Comment by pacak** [comment]
Pushed, wording might change in some places but cli tests are passing as is so hopefully nothing breaks.

Also added a way for users to make cli parser output more colorful a-la clap3/clap4 if they want to. No extra dependencies by default.

**Comment by Shnatsel** [comment]
It's a little strange to resolve color as a compilation feature. This is usually runtime configuration - and is disabled by default when writing to something other than a terminal, so that the plain text file doesn't end up littered with terminal escape sequences. See e.g. the behavior of `grep --color=` where it defaults to auto, but can be explicitly enabled or disabled.

Is there a way to do runtime resolution with `bpaf`? If not, I'd rather stick to plain/colorless output so that the output dumped to a text file would still be readable.

**Comment by pacak** [comment]
Runtime detection is present as well and will be used if you enable either colorscheme so redirect to file or running in CI would work as expected. Having it as a compile time helps people to decide if they want any colors at all - I would prefer no colors so won't be enabling this feature, but some people like it.

**Comment by Shnatsel** [comment]
My apologies for the delay, I got caught up in RL stuff.  I'll try to review and merge this next week.

**Comment by pacak** [comment]
> My apologies for the delay, I got caught up in RL stuff. I'll try to review and merge this next week.

No worries, take your time.

**Comment by pacak** [comment]
Any thoughts? Also do you want a pull request for `cargo-auditable`?  `pico-args` is simple but correctness is not quite there - see https://github.com/RazrFalcon/pico-args/issues/15 for example.

**Comment by Shnatsel** [comment]
Thank you for the reminder, I'll try to take a look in the next few days now that I've shipped `cargo audit` 0.17.3.

`cargo auditable` doesn't need any help generation, and it only capture a subset of all arguments passed. Basically I'm intercepting only *some* of the arguments passed to rustc, for which `pico-args` is a great fit.

I am aware of the correctness issue you mentioned, but it only matters for invalid argument sequences, and rustc itself already does an argument validation pass so we don't have to.

**Comment by pacak** [comment]
> I'm going to make the stylistic choice of bright colors, and drop the feature.

There's no downside to leaving the feature in even if you go with the bright colors by default, for example I would prefer not having color at all compared to the bright option. Visibility depends on only on background being dark or bright, but also on a palette.

**Comment by pacak** [comment]
https://github.com/clap-rs/clap/discussions/2906#discussioncomment-1646705

**Comment by pacak** [comment]
Also if you really want to drop the color selection - you need to update the docs.

**Comment by Shnatsel** [comment]
Actually, I'll have to disable color for now because it pulls in `atty`, which has known UB and appears to be unmaintained: https://github.com/softprops/atty/issues/50

**Comment by pacak** [comment]
Bummer. I'm not using it directly but through owo-colors. Do you know of
any working/maintained alternative?

**Comment by Shnatsel** [comment]
No, but I haven't really looked.

You could always just fork it and we can encourage people to switch via the RustSec advisory for example: https://github.com/rustsec/advisory-db/issues/1457

**Comment by Shnatsel** [comment]
I've shipped v0.3.2 - without color, but it does update to `bpaf` 0.7.x on crates.io.

I'd be happy to add color later because I think it meaningfully improves the readability of the help text.

**Comment by pacak** [comment]
I'll see what I can do about `atty` - I have some other changes planned first. Maybe a week or two.

**Comment by pacak** [comment]
I did this for now FWIW https://github.com/zkat/supports-color/issues/9

**Comment by pacak** [comment]
supports-color pull request got merged, hopefully a release soon.

**Pull request merged**
